name: franceinfo_app
description: A Franceinfo reader app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  http: ^0.13.5
  shared_preferences: ^2.0.15
  webfeed: ^0.7.0
  share_plus: ^4.0.10+1
  url_launcher: ^6.1.5
  google_fonts: ^3.0.1
  connectivity_plus: ^2.3.6+1
  html_unescape: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
    - images/

  fonts:
    - family: Zen Kaku Gothic Antique
      fonts:
        - asset: fonts/ZenKakuGothicAntique.ttf